name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip the code
      run: zip -r tiangong-lca-data-${{ github.ref }}.zip tiangong_lca_data

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tiangong-lca-data-${{ github.ref }}.zip
          LICENSE
