name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Get tag name
      id: tag_name
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: Zip the code
      run: cd tiangong_lca_data && zip -r ../tiangong-lca-data-${{ steps.tag_name.outputs.TAG_NAME }}.zip *

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tiangong-lca-data-${{ steps.tag_name.outputs.TAG_NAME }}.zip
          LICENSE
        body_path: ./release_notes/${{ steps.tag_name.outputs.TAG_NAME }}.md        
